apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:alpine3.16
    ports: 
    - containerPort: 6379
    resources:
      limits:
        memory: "900Mi"
        cpu: "900m"
      requests:
        memory: "700Mi"
        cpu: "600m"