apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:alpine3.16
    ports: 
    - containerPort: 5432 
    env:
      - name: POSTGRES_DB
        value: postgres
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres