apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.5.48
    ports: 
    - containerPort: 3306 
    env:
      - name: MYSQL_DATABASE
        value: mysql
      - name: MYSQL_USER
        value: root
      - name: MYSQL_ROOT_PASSWORD
        value: root
    resources:
      limits:
        memory: "512Mi"
        cpu: "100m"
      requests:
        memory: "512Mi"
        cpu: "100m"